### ISSUE TITLE
Unable to build `@jupytergis/base`

### ISSUE THREAD

**Issue by arjxn-py** [geojupyter/jupytergis#102]
During the build process of the `@jupytergis/base`, I encountered multiple warnings and errors related to fetching map tiles and processing images. Below are the error logs.

```python
 Traceback (most recent call last):
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connection.py", line 196, in _new_conn
           sock = connection.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
           raise err
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
           sock.connect(sa)
       TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

       The above exception was the direct cause of the following exception:

       Traceback (most recent call last):
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
           response = self._make_request(
                      ^^^^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
           raise new_e
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
           self._validate_conn(conn)
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
           conn.connect()
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connection.py", line 615, in connect
           self.sock = sock = self._new_conn()
                              ^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connection.py", line 205, in _new_conn
           raise ConnectTimeoutError(
       urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000002BBA36C4A10>, 'Connection to a.tile.opentopomap.org timed out. (connect timeout=None)')

       The above exception was the direct cause of the following exception:

       Traceback (most recent call last):
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\requests\adapters.py", line 667, in send
           resp = conn.urlopen(
                  ^^^^^^^^^^^^^
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
           retries = retries.increment(
                     ^^^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
           raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='a.tile.opentopomap.org', port=443): Max retries exceeded with url: /5/5/12.png (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002BBA36C4A10>, 'Connection to a.tile.opentopomap.org timed out. (connect timeout=None)'))
```

<details>
<summary>Full error logs</summary>
<br>

```
√  @jupytergis/schema:build (9s)

    ×  @jupytergis/base:build
       C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\PIL\Image.py:1056: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
         warnings.warn(
       Process OpenStreetMap Mapnik
          Fetch https://tile.openstreetmap.org/5/16/11.png
          Fetch https://tile.openstreetmap.org/5/17/11.png
          Fetch https://tile.openstreetmap.org/5/16/12.png
          Fetch https://tile.openstreetmap.org/5/17/12.png
       Process OpenStreetMap DE
          Fetch https://tile.openstreetmap.de/8/135/85.png
          Fetch https://tile.openstreetmap.de/8/136/85.png
          Fetch https://tile.openstreetmap.de/8/135/86.png
          Fetch https://tile.openstreetmap.de/8/136/86.png
       Process OpenStreetMap CH
          Fetch https://tile.osm.ch/switzerland/8/133/90.png
          Fetch https://tile.osm.ch/switzerland/8/134/90.png
          Fetch https://tile.osm.ch/switzerland/8/133/91.png
          Fetch https://tile.osm.ch/switzerland/8/134/91.png
       Process OpenStreetMap France
          Fetch https://a.tile.openstreetmap.fr/osmfr/5/16/11.png
          Fetch https://a.tile.openstreetmap.fr/osmfr/5/17/11.png
          Fetch https://a.tile.openstreetmap.fr/osmfr/5/16/12.png
          Fetch https://a.tile.openstreetmap.fr/osmfr/5/17/12.png
       Process OpenStreetMap HOT
          Fetch https://a.tile.openstreetmap.fr/hot/5/16/11.png
          Fetch https://a.tile.openstreetmap.fr/hot/5/17/11.png
          Fetch https://a.tile.openstreetmap.fr/hot/5/16/12.png
          Fetch https://a.tile.openstreetmap.fr/hot/5/17/12.png
       Process OpenStreetMap BZH
          Fetch https://tile.openstreetmap.bzh/br/8/125/89.png
          Fetch https://tile.openstreetmap.bzh/br/8/126/89.png
          Fetch https://tile.openstreetmap.bzh/br/8/125/90.png
          Fetch https://tile.openstreetmap.bzh/br/8/126/90.png
       Process OpenStreetMap BlackAndWhite
          Fetch http://a.tiles.wmflabs.org/bw-mapnik/5/16/11.png
       Failed... HTTPConnectionPool(host='a.tiles.wmflabs.org', port=80): Max retries exceeded with url: /bw-mapnik/5/16/11.png (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002BBA36690D0>: Failed to resolve 'a.tiles.wmflabs.org' ([Errno 11001] getaddrinfo failed)"))
       Process NASAGIBS ModisTerraTrueColorCR
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_CorrectedReflectance_TrueColor/default/2024-08-20/GoogleMapsCompatible_Level9/5/11/16.jpg  
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_CorrectedReflectance_TrueColor/default/2024-08-20/GoogleMapsCompatible_Level9/5/11/17.jpg  
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_CorrectedReflectance_TrueColor/default/2024-08-20/GoogleMapsCompatible_Level9/5/12/16.jpg  
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_CorrectedReflectance_TrueColor/default/2024-08-20/GoogleMapsCompatible_Level9/5/12/17.jpg  
       Process NASAGIBS ModisTerraBands367CR
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_CorrectedReflectance_Bands367/default/2024-08-20/GoogleMapsCompatible_Level9/5/11/16.jpg   
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_CorrectedReflectance_Bands367/default/2024-08-20/GoogleMapsCompatible_Level9/5/11/17.jpg   
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_CorrectedReflectance_Bands367/default/2024-08-20/GoogleMapsCompatible_Level9/5/12/16.jpg   
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_CorrectedReflectance_Bands367/default/2024-08-20/GoogleMapsCompatible_Level9/5/12/17.jpg   
       Process NASAGIBS ViirsEarthAtNight2012
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/VIIRS_CityLights_2012/default/2024-08-20/GoogleMapsCompatible_Level8/5/11/16.jpg
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/VIIRS_CityLights_2012/default/2024-08-20/GoogleMapsCompatible_Level8/5/11/17.jpg
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/VIIRS_CityLights_2012/default/2024-08-20/GoogleMapsCompatible_Level8/5/12/16.jpg
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/VIIRS_CityLights_2012/default/2024-08-20/GoogleMapsCompatible_Level8/5/12/17.jpg
       Process NASAGIBS ModisTerraLSTDay
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_Land_Surface_Temp_Day/default/2024-08-20/GoogleMapsCompatible_Level7/5/11/16.png
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_Land_Surface_Temp_Day/default/2024-08-20/GoogleMapsCompatible_Level7/5/11/17.png
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_Land_Surface_Temp_Day/default/2024-08-20/GoogleMapsCompatible_Level7/5/12/16.png
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_Land_Surface_Temp_Day/default/2024-08-20/GoogleMapsCompatible_Level7/5/12/17.png
       Process NASAGIBS ModisTerraSnowCover
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_NDSI_Snow_Cover/default/2024-08-20/GoogleMapsCompatible_Level8/5/11/16.png
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_NDSI_Snow_Cover/default/2024-08-20/GoogleMapsCompatible_Level8/5/11/17.png
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_NDSI_Snow_Cover/default/2024-08-20/GoogleMapsCompatible_Level8/5/12/16.png
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_NDSI_Snow_Cover/default/2024-08-20/GoogleMapsCompatible_Level8/5/12/17.png
       Process NASAGIBS ModisTerraAOD
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_Aerosol/default/2024-08-20/GoogleMapsCompatible_Level6/5/11/16.png
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_Aerosol/default/2024-08-20/GoogleMapsCompatible_Level6/5/11/17.png
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_Aerosol/default/2024-08-20/GoogleMapsCompatible_Level6/5/12/16.png
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_Aerosol/default/2024-08-20/GoogleMapsCompatible_Level6/5/12/17.png
       Process NASAGIBS ModisTerraChlorophyll
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_L2_Chlorophyll_A/default/2024-08-20/GoogleMapsCompatible_Level7/5/11/16.png
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_L2_Chlorophyll_A/default/2024-08-20/GoogleMapsCompatible_Level7/5/11/17.png
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_L2_Chlorophyll_A/default/2024-08-20/GoogleMapsCompatible_Level7/5/12/16.png
          Fetch https://map1.vis.earthdata.nasa.gov/wmts-webmerc/MODIS_Terra_L2_Chlorophyll_A/default/2024-08-20/GoogleMapsCompatible_Level7/5/12/17.png
       Process NASAGIBS ModisTerraBands721CR
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_Bands721/default/2024-08-20/GoogleMapsCompatible_Level9/5/11/16.jpg 
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_Bands721/default/2024-08-20/GoogleMapsCompatible_Level9/5/11/17.jpg 
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_Bands721/default/2024-08-20/GoogleMapsCompatible_Level9/5/12/16.jpg 
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_Bands721/default/2024-08-20/GoogleMapsCompatible_Level9/5/12/17.jpg 
       Process NASAGIBS ModisAquaTrueColorCR
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Aqua_CorrectedReflectance_TrueColor/default/2024-08-20/GoogleMapsCompatible_Level9/5/11/16.jpg 
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Aqua_CorrectedReflectance_TrueColor/default/2024-08-20/GoogleMapsCompatible_Level9/5/11/17.jpg 
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Aqua_CorrectedReflectance_TrueColor/default/2024-08-20/GoogleMapsCompatible_Level9/5/12/16.jpg 
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Aqua_CorrectedReflectance_TrueColor/default/2024-08-20/GoogleMapsCompatible_Level9/5/12/17.jpg 
       Process NASAGIBS ModisAquaBands721CR
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Aqua_CorrectedReflectance_Bands721/default/2024-08-20/GoogleMapsCompatible_Level9/5/11/16.jpg  
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Aqua_CorrectedReflectance_Bands721/default/2024-08-20/GoogleMapsCompatible_Level9/5/11/17.jpg  
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Aqua_CorrectedReflectance_Bands721/default/2024-08-20/GoogleMapsCompatible_Level9/5/12/16.jpg  
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Aqua_CorrectedReflectance_Bands721/default/2024-08-20/GoogleMapsCompatible_Level9/5/12/17.jpg  
       Process NASAGIBS ViirsTrueColorCR
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/VIIRS_SNPP_CorrectedReflectance_TrueColor/default/2024-08-20/GoogleMapsCompatible_Level9/5/11/16.jpg 
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/VIIRS_SNPP_CorrectedReflectance_TrueColor/default/2024-08-20/GoogleMapsCompatible_Level9/5/11/17.jpg 
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/VIIRS_SNPP_CorrectedReflectance_TrueColor/default/2024-08-20/GoogleMapsCompatible_Level9/5/12/16.jpg 
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/VIIRS_SNPP_CorrectedReflectance_TrueColor/default/2024-08-20/GoogleMapsCompatible_Level9/5/12/17.jpg 
       Process NASAGIBS BlueMarble3413
       Process NASAGIBS BlueMarble3031
       Process NASAGIBS BlueMarbleBathymetry3413
       Process NASAGIBS BlueMarbleBathymetry3031
       Process NASAGIBS MEaSUREsIceVelocity3413
       Process NASAGIBS MEaSUREsIceVelocity3031
       Process NASAGIBS ASTER_GDEM_Greyscale_Shaded_Relief
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/ASTER_GDEM_Greyscale_Shaded_Relief/default/GoogleMapsCompatible_Level12/5/11/16.jpg
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/ASTER_GDEM_Greyscale_Shaded_Relief/default/GoogleMapsCompatible_Level12/5/11/17.jpg
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/ASTER_GDEM_Greyscale_Shaded_Relief/default/GoogleMapsCompatible_Level12/5/12/16.jpg
          Fetch https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/ASTER_GDEM_Greyscale_Shaded_Relief/default/GoogleMapsCompatible_Level12/5/12/17.jpg
       Process USGS USTopo
          Fetch https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/5/12/5
          Fetch https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/5/12/6
          Fetch https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/5/13/5
          Fetch https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/5/13/6
       Process USGS USImagery
          Fetch https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer/tile/5/12/5
          Fetch https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer/tile/5/12/6
          Fetch https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer/tile/5/13/5
          Fetch https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer/tile/5/13/6
       Process USGS USImageryTopo
          Fetch https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryTopo/MapServer/tile/5/12/5
          Fetch https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryTopo/MapServer/tile/5/12/6
          Fetch https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryTopo/MapServer/tile/5/13/5
          Fetch https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryTopo/MapServer/tile/5/13/6
       Process WaymarkedTrails hiking
          Fetch https://tile.waymarkedtrails.org/hiking/5/16/11.png
          Fetch https://tile.waymarkedtrails.org/hiking/5/17/11.png
          Fetch https://tile.waymarkedtrails.org/hiking/5/16/12.png
          Fetch https://tile.waymarkedtrails.org/hiking/5/17/12.png
       Process WaymarkedTrails cycling
          Fetch https://tile.waymarkedtrails.org/cycling/5/16/11.png
          Fetch https://tile.waymarkedtrails.org/cycling/5/17/11.png
          Fetch https://tile.waymarkedtrails.org/cycling/5/16/12.png
          Fetch https://tile.waymarkedtrails.org/cycling/5/17/12.png
       Process WaymarkedTrails mtb
          Fetch https://tile.waymarkedtrails.org/mtb/5/16/11.png
          Fetch https://tile.waymarkedtrails.org/mtb/5/17/11.png
          Fetch https://tile.waymarkedtrails.org/mtb/5/16/12.png
          Fetch https://tile.waymarkedtrails.org/mtb/5/17/12.png
       Process WaymarkedTrails slopes
          Fetch https://tile.waymarkedtrails.org/slopes/5/16/11.png
          Fetch https://tile.waymarkedtrails.org/slopes/5/17/11.png
          Fetch https://tile.waymarkedtrails.org/slopes/5/16/12.png
          Fetch https://tile.waymarkedtrails.org/slopes/5/17/12.png
       Process WaymarkedTrails riding
          Fetch https://tile.waymarkedtrails.org/riding/5/16/11.png
          Fetch https://tile.waymarkedtrails.org/riding/5/17/11.png
          Fetch https://tile.waymarkedtrails.org/riding/5/16/12.png
          Fetch https://tile.waymarkedtrails.org/riding/5/17/12.png
       Process WaymarkedTrails skating
          Fetch https://tile.waymarkedtrails.org/skating/5/16/11.png
          Fetch https://tile.waymarkedtrails.org/skating/5/17/11.png
          Fetch https://tile.waymarkedtrails.org/skating/5/16/12.png
          Fetch https://tile.waymarkedtrails.org/skating/5/17/12.png
       Process Gaode Normal
          Fetch http://webrd01.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=7&x=5&y=12&z=5
       Failed... HTTPConnectionPool(host='webrd01.is.autonavi.com', port=80): Max retries exceeded with url: /appmaptile?lang=zh_cn&size=1&scale=1&style=7&x=5&y=12&z=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002BBA36C6410>, 'Connection to webrd01.is.autonavi.com timed out. (connect timeout=None)'))
       Process Gaode Satellite
          Fetch http://webst01.is.autonavi.com/appmaptile?style=6&x=5&y=12&z=5
          Fetch http://webst01.is.autonavi.com/appmaptile?style=6&x=6&y=12&z=5
          Fetch http://webst01.is.autonavi.com/appmaptile?style=6&x=5&y=13&z=5
          Fetch http://webst01.is.autonavi.com/appmaptile?style=6&x=6&y=13&z=5
       Process Strava All
          Fetch https://heatmap-external-a.strava.com/tiles/all/hot/5/16/11.png
          Fetch https://heatmap-external-a.strava.com/tiles/all/hot/5/17/11.png
          Fetch https://heatmap-external-a.strava.com/tiles/all/hot/5/16/12.png
          Fetch https://heatmap-external-a.strava.com/tiles/all/hot/5/17/12.png
       Process Strava Ride
          Fetch https://heatmap-external-a.strava.com/tiles/ride/hot/5/16/11.png
          Fetch https://heatmap-external-a.strava.com/tiles/ride/hot/5/17/11.png
          Fetch https://heatmap-external-a.strava.com/tiles/ride/hot/5/16/12.png
          Fetch https://heatmap-external-a.strava.com/tiles/ride/hot/5/17/12.png
       Process Strava Run
          Fetch https://heatmap-external-a.strava.com/tiles/run/bluered/5/16/11.png
          Fetch https://heatmap-external-a.strava.com/tiles/run/bluered/5/17/11.png
          Fetch https://heatmap-external-a.strava.com/tiles/run/bluered/5/16/12.png
          Fetch https://heatmap-external-a.strava.com/tiles/run/bluered/5/17/12.png
       Process Strava Water
          Fetch https://heatmap-external-a.strava.com/tiles/water/blue/5/16/11.png
          Fetch https://heatmap-external-a.strava.com/tiles/water/blue/5/17/11.png
          Fetch https://heatmap-external-a.strava.com/tiles/water/blue/5/16/12.png
          Fetch https://heatmap-external-a.strava.com/tiles/water/blue/5/17/12.png
       Process Strava Winter
          Fetch https://heatmap-external-a.strava.com/tiles/winter/hot/5/16/11.png
          Fetch https://heatmap-external-a.strava.com/tiles/winter/hot/5/17/11.png
          Fetch https://heatmap-external-a.strava.com/tiles/winter/hot/5/16/12.png
          Fetch https://heatmap-external-a.strava.com/tiles/winter/hot/5/17/12.png
       Process OPNVKarte
          Fetch https://tileserver.memomaps.de/tilegen/5/5/12.png
          Fetch https://tileserver.memomaps.de/tilegen/5/6/12.png
          Fetch https://tileserver.memomaps.de/tilegen/5/5/13.png
          Fetch https://tileserver.memomaps.de/tilegen/5/6/13.png
       Process OpenTopoMap
          Fetch https://a.tile.opentopomap.org/5/5/12.png
       Traceback (most recent call last):
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connection.py", line 196, in _new_conn
           sock = connection.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
           raise err
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
           sock.connect(sa)
       TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

       The above exception was the direct cause of the following exception:

       Traceback (most recent call last):
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
           response = self._make_request(
                      ^^^^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
           raise new_e
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
           self._validate_conn(conn)
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
           conn.connect()
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connection.py", line 615, in connect
           self.sock = sock = self._new_conn()
                              ^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connection.py", line 205, in _new_conn
           raise ConnectTimeoutError(
       urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000002BBA36C4A10>, 'Connection to a.tile.opentopomap.org timed out. (connect timeout=None)')

       The above exception was the direct cause of the following exception:

       Traceback (most recent call last):
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\requests\adapters.py", line 667, in send
           resp = conn.urlopen(
                  ^^^^^^^^^^^^^
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
           retries = retries.increment(
                     ^^^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
           raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='a.tile.opentopomap.org', port=443): Max retries exceeded with url: /5/5/12.png (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002BBA36C4A10>, 'Connection to a.tile.opentopomap.org timed out. (connect timeout=None)'))

       During handling of the above exception, another exception occurred:

       Traceback (most recent call last):
         File "C:\Users\Arjun\Desktop\Arjun\jupytergis\packages\base\rasterlayer_gallery_generator.py", line 193, in <module>
           file_path = download_thumbnail(url_template, name, position, tile_size)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\Desktop\Arjun\jupytergis\packages\base\rasterlayer_gallery_generator.py", line 158, in download_thumbnail
           thumbnail = create_thumbnail(
                       ^^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\Desktop\Arjun\jupytergis\packages\base\rasterlayer_gallery_generator.py", line 46, in create_thumbnail
           tile = fetch_tile(url_template, tile_x, tile_y, zoom)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\Desktop\Arjun\jupytergis\packages\base\rasterlayer_gallery_generator.py", line 20, in fetch_tile
           response = requests.get(url, headers={
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\requests\api.py", line 73, in get
           return request("get", url, params=params, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\requests\api.py", line 59, in request
           return session.request(method=method, url=url, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\requests\sessions.py", line 589, in request
           resp = self.send(prep, **send_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\requests\sessions.py", line 703, in send
           r = adapter.send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "C:\Users\Arjun\miniconda3\envs\jgis\Lib\site-packages\requests\adapters.py", line 688, in send
           raise ConnectTimeout(e, request=request)
       requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='a.tile.opentopomap.org', port=443): Max retries exceeded with url: /5/5/12.png (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002BBA36C4A10>, 'Connection to a.tile.opentopomap.org timed out. (connect timeout=None)'))
```

</details>

**Comment by martinRenou** [comment]
Thanks for opening an issue! 

This is unfortunate, I thought this part of the code would not prevent the build from passing and we would simply ignore those failing requests.

Just for your information, these requests are for populating the raster-tiles gallery with nice image in the UI.

You should be able to bypass this for now with `jlpm run build:dev`, although I'm not 100% sure this will build everything you need.

**Comment by arjxn-py** [comment]
Thanks for the quick response @martinRenou, I'll do as suggested.

**Comment by arjxn-py** [comment]
> I thought this part of the code

I'd be happy to know which part of code is resulting in this as I'm not sure.

**Comment by martinRenou** [comment]
It's this Python script which downloads all the gallery images at build time https://github.com/QuantStack/jupytergis/blob/main/packages/base/rasterlayer_gallery_generator.py. It is being used by this NPM script https://github.com/QuantStack/jupytergis/blob/main/packages/base/package.json#L31 during the build of jupytergis
