### ISSUE TITLE
Unable to create new `.jGIS` document

### ISSUE THREAD

**Issue by arjxn-py** [geojupyter/jupytergis#182]
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/e32c00ae-4eb4-4552-94b8-ec8de17aabe7">

With this error message I get the following logs in jupyterlab terminal: 

```
[E 2024-10-10 16:23:31.648 ServerApp] Error initializing: examples/untitled.jGIS
    JSONDecodeError('Expecting property name enclosed in double quotes: line 6 column 1 (char 160)')
    Traceback (most recent call last):
      File "/Users/arjunverma/mambaforge/envs/jgis/lib/python3.12/site-packages/jupyter_collaboration/handlers.py", line 233, in open
        await self.room.initialize()
      File "/Users/arjunverma/mambaforge/envs/jgis/lib/python3.12/site-packages/jupyter_collaboration/rooms.py", line 148, in initialize
        self._document.source = model["content"]
        ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/arjunverma/mambaforge/envs/jgis/lib/python3.12/site-packages/jupyter_ydoc/ybasedoc.py", line 95, in source
        return self.set(value)
               ^^^^^^^^^^^^^^^
      File "/Users/arjunverma/Desktop/Arjun/jupytergis/python/jupytergis_core/jupytergis_core/jgis_ydoc.py", line 47, in set
        valueDict = json.loads(value)
                    ^^^^^^^^^^^^^^^^^
      File "/Users/arjunverma/mambaforge/envs/jgis/lib/python3.12/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/arjunverma/mambaforge/envs/jgis/lib/python3.12/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/arjunverma/mambaforge/envs/jgis/lib/python3.12/json/decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
                   ^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by martinRenou** [comment]
Could it be related to https://github.com/jupytercad/JupyterCAD/issues/471 ?

**Comment by arjxn-py** [comment]
> Could it be related to [jupytercad/JupyterCAD#471](https://github.com/jupytercad/JupyterCAD/issues/471) ?

Yes, it could be. 
But just to mention that there was no trouble opening any of the example files.

**Comment by arjxn-py** [comment]
> Man, thanks for reporting this. I left a comma in #170 😓
> 
> #184 should fix it

Ou, I'm glad it was caught and fixed. Thanks, it was quick 🚀
